files:
  - source: '**/*.*'
    translation: /%locale%/%file_name%.%locale%.%file_extension%
    content_segmentation: 0
    translatable_elements:
      - '/WorkspaceLocalizableSchemasData/SchemaData/Row/Column[@Value]'
