files:
  - source: '*.xml'
    translation: '%original_file_name%'
    content_segmentation: 0
    translatable_elements:
      - '/WorkspaceResources/Package/PackageResources/Resources/Group/Items/Item[@Value]'
      - '/WorkspaceLocalizableSchemasData/SchemaData/Row/Column[@Value]'
